apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: argocd
  name: argocd-app
spec:
  project: argocd-project
  source:
    repoURL: https://github.com/AnasZineddine/azineddi-aelamran-p3.git
    targetRevision: HEAD
    path: dev
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
