apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd
        image: wil42/playground:v1
        ports:
        - containerPort: 8080
